// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: AddUserCredits.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addUserCredits = `-- name: AddUserCredits :one
UPDATE users
SET balance_credits_int = balance_credits_int + $2
WHERE user_id = $1
RETURNING user_id, username, email, password, balance_credits_int
`

type AddUserCreditsParams struct {
	UserID            uuid.UUID
	BalanceCreditsInt int32
}

func (q *Queries) AddUserCredits(ctx context.Context, arg AddUserCreditsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUserCredits, arg.UserID, arg.BalanceCreditsInt)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.BalanceCreditsInt,
	)
	return i, err
}
