// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateApiKey.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (user_id,name,key_hash,api_key_show_string)
VALUES(
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, name, key_hash, disabled, deleted, last_used_at, disabled_at, deleted_at, api_key_show_string
`

type CreateApiKeyParams struct {
	UserID           uuid.UUID
	Name             string
	KeyHash          string
	ApiKeyShowString string
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createApiKey,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.ApiKeyShowString,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Disabled,
		&i.Deleted,
		&i.LastUsedAt,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.ApiKeyShowString,
	)
	return i, err
}
