// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateTransaction.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO razorpay_transactions (user_id, amt, credits, status)
VALUES ($1, $2, $3, $4)
RETURNING transaction_id, user_id, amt, credits, status, started_at, completed_at
`

type CreateTransactionParams struct {
	UserID  uuid.UUID
	Amt     int32
	Credits int32
	Status  string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (RazorpayTransaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Amt,
		arg.Credits,
		arg.Status,
	)
	var i RazorpayTransaction
	err := row.Scan(
		&i.TransactionID,
		&i.UserID,
		&i.Amt,
		&i.Credits,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
