// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetApiKeys.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getApiKeys = `-- name: GetApiKeys :many
SELECT name,api_key_show_string,disabled,deleted,last_used_at,disabled_at,deleted_at FROM api_keys 
WHERE user_id = $1
ORDER BY last_used_at DESC
`

type GetApiKeysRow struct {
	Name             string
	ApiKeyShowString string
	Disabled         bool
	Deleted          bool
	LastUsedAt       sql.NullTime
	DisabledAt       sql.NullTime
	DeletedAt        sql.NullTime
}

func (q *Queries) GetApiKeys(ctx context.Context, userID uuid.UUID) ([]GetApiKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, getApiKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApiKeysRow
	for rows.Next() {
		var i GetApiKeysRow
		if err := rows.Scan(
			&i.Name,
			&i.ApiKeyShowString,
			&i.Disabled,
			&i.Deleted,
			&i.LastUsedAt,
			&i.DisabledAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
