// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetUserBalance.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserBalance = `-- name: GetUserBalance :one
SELECT balance_credits_int FROM users WHERE user_id = $1
`

func (q *Queries) GetUserBalance(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserBalance, userID)
	var balance_credits_int int32
	err := row.Scan(&balance_credits_int)
	return balance_credits_int, err
}
