// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	KeyHash    string
	Disabled   bool
	Deleted    bool
	LastUsedAt sql.NullTime
	DisabledAt sql.NullTime
	DeletedAt  sql.NullTime
}

type DeployedModel struct {
	DeployedModelID uuid.UUID
	DeployerID      uuid.UUID
	ModelID         uuid.UUID
	InputCost       int32
	OutputCost      int32
}

type Deployer struct {
	DeployerID   uuid.UUID
	DeployerName string
}

type Model struct {
	ModelID   uuid.UUID
	ModelName string
	Slug      string
	Company   string
}

type RazorpayTransaction struct {
	TransactionID uuid.UUID
	UserID        uuid.UUID
	Amt           int32
	Credits       int32
	Status        string
	StartedAt     time.Time
	CompletedAt   sql.NullTime
}

type User struct {
	UserID            uuid.UUID
	Username          string
	Email             string
	Password          string
	BalanceCreditsInt int32
}

type UserUsage struct {
	ApikeyID        uuid.UUID
	UserID          uuid.UUID
	DeployedModelID uuid.UUID
	InputTokens     int32
	OutputTokens    int32
	Query           string
	Resp            string
	CreditsUsed     int32
}
