// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: RevokeApiKey.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const revokeApiKey = `-- name: RevokeApiKey :one
UPDATE api_keys
SET disabled = true,
    disabled_at = now()
WHERE id = $1 AND user_id = $2 AND deleted = false AND disabled = false
RETURNING id, user_id, name, key_hash, disabled, deleted, last_used_at, disabled_at, deleted_at, api_key_show_string
`

type RevokeApiKeyParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, revokeApiKey, arg.ID, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Disabled,
		&i.Deleted,
		&i.LastUsedAt,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.ApiKeyShowString,
	)
	return i, err
}
