// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: UpdateTransactionStatus.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE razorpay_transactions
SET status = $2, completed_at = now()
WHERE transaction_id = $1
RETURNING transaction_id, user_id, amt, credits, status, started_at, completed_at
`

type UpdateTransactionStatusParams struct {
	TransactionID uuid.UUID
	Status        string
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (RazorpayTransaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionStatus, arg.TransactionID, arg.Status)
	var i RazorpayTransaction
	err := row.Scan(
		&i.TransactionID,
		&i.UserID,
		&i.Amt,
		&i.Credits,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
