// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package dbquery

import (
	"context"
)

const createUserTeamAPIKey = `-- name: CreateUserTeamAPIKey :one
INSERT INTO user_team_api_keys (id, org_id, team_id, user_id, key_hash, key_prefix, is_active)
VALUES ($1, $2, $3, $4, $5, $6, TRUE)
RETURNING id, org_id, team_id, user_id, key_hash, key_prefix, revoked_at, is_active, last_used_at, created_at
`

type CreateUserTeamAPIKeyParams struct {
	ID        string
	OrgID     string
	TeamID    string
	UserID    string
	KeyHash   string
	KeyPrefix string
}

func (q *Queries) CreateUserTeamAPIKey(ctx context.Context, arg CreateUserTeamAPIKeyParams) (UserTeamApiKey, error) {
	row := q.db.QueryRowContext(ctx, createUserTeamAPIKey,
		arg.ID,
		arg.OrgID,
		arg.TeamID,
		arg.UserID,
		arg.KeyHash,
		arg.KeyPrefix,
	)
	var i UserTeamApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TeamID,
		&i.UserID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.RevokedAt,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveUserTeamAPIKeyByHash = `-- name: GetActiveUserTeamAPIKeyByHash :one
SELECT id, org_id, team_id, user_id, key_hash, key_prefix, revoked_at, is_active, last_used_at, created_at
FROM user_team_api_keys
WHERE key_hash = $1
  AND is_active = TRUE
  AND revoked_at IS NULL
`

func (q *Queries) GetActiveUserTeamAPIKeyByHash(ctx context.Context, keyHash string) (UserTeamApiKey, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserTeamAPIKeyByHash, keyHash)
	var i UserTeamApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TeamID,
		&i.UserID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.RevokedAt,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserTeamAPIKeys = `-- name: ListUserTeamAPIKeys :many
SELECT id, org_id, team_id, user_id, key_hash, key_prefix, revoked_at, is_active, last_used_at, created_at
FROM user_team_api_keys
WHERE org_id = $1 AND team_id = $2 AND user_id = $3
ORDER BY created_at DESC
`

type ListUserTeamAPIKeysParams struct {
	OrgID  string
	TeamID string
	UserID string
}

func (q *Queries) ListUserTeamAPIKeys(ctx context.Context, arg ListUserTeamAPIKeysParams) ([]UserTeamApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listUserTeamAPIKeys, arg.OrgID, arg.TeamID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserTeamApiKey
	for rows.Next() {
		var i UserTeamApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TeamID,
			&i.UserID,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.RevokedAt,
			&i.IsActive,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserTeamAPIKey = `-- name: RevokeUserTeamAPIKey :execrows
UPDATE user_team_api_keys
SET is_active = FALSE,
    revoked_at = NOW()
WHERE id = $1
  AND org_id = $2
  AND revoked_at IS NULL
`

type RevokeUserTeamAPIKeyParams struct {
	ID    string
	OrgID string
}

func (q *Queries) RevokeUserTeamAPIKey(ctx context.Context, arg RevokeUserTeamAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeUserTeamAPIKey, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
