// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbquery

import (
	"context"
	"database/sql"
	"time"
)

const consumeMagicLink = `-- name: ConsumeMagicLink :one
UPDATE auth_magic_links
SET consumed_at = NOW()
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
RETURNING id, org_id, email, code_hash, expires_at, consumed_at, created_at
`

func (q *Queries) ConsumeMagicLink(ctx context.Context, id string) (AuthMagicLink, error) {
	row := q.db.QueryRowContext(ctx, consumeMagicLink, id)
	var i AuthMagicLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMagicLink = `-- name: CreateMagicLink :one
INSERT INTO auth_magic_links (id, org_id, email, code_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, email, code_hash, expires_at, consumed_at, created_at
`

type CreateMagicLinkParams struct {
	ID        string
	OrgID     string
	Email     string
	CodeHash  string
	ExpiresAt time.Time
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (AuthMagicLink, error) {
	row := q.db.QueryRowContext(ctx, createMagicLink,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i AuthMagicLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO auth_refresh_tokens (id, org_id, user_id, token_hash, session_id, device_info, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, user_id, token_hash, session_id, device_info, expires_at, revoked_at, last_used_at, created_at
`

type CreateRefreshTokenParams struct {
	ID         string
	OrgID      string
	UserID     string
	TokenHash  string
	SessionID  string
	DeviceInfo sql.NullString
	ExpiresAt  time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (AuthRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.TokenHash,
		arg.SessionID,
		arg.DeviceInfo,
		arg.ExpiresAt,
	)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TokenHash,
		&i.SessionID,
		&i.DeviceInfo,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT id, org_id, user_id, token_hash, session_id, device_info, expires_at, revoked_at, last_used_at, created_at
FROM auth_refresh_tokens
WHERE id = $1
`

func (q *Queries) GetRefreshTokenByID(ctx context.Context, id string) (AuthRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByID, id)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TokenHash,
		&i.SessionID,
		&i.DeviceInfo,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE auth_refresh_tokens
SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeRefreshToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchRefreshToken = `-- name: TouchRefreshToken :execrows
UPDATE auth_refresh_tokens
SET last_used_at = NOW()
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) TouchRefreshToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchRefreshToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
