// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbquery

import (
	"context"
	"database/sql"
	"time"
)

const consumeMagicLink = `-- name: ConsumeMagicLink :one
UPDATE auth_magic_links
SET consumed_at = NOW()
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
RETURNING id, org_id, email, code_hash, expires_at, consumed_at, created_at
`

func (q *Queries) ConsumeMagicLink(ctx context.Context, id string) (AuthMagicLink, error) {
	row := q.db.QueryRowContext(ctx, consumeMagicLink, id)
	var i AuthMagicLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeMagicLinkByCode = `-- name: ConsumeMagicLinkByCode :one
UPDATE auth_magic_links
SET consumed_at = NOW()
WHERE id = $1
  AND code_hash = $2
  AND consumed_at IS NULL
  AND expires_at > NOW()
RETURNING id, org_id, email, code_hash, expires_at, consumed_at, created_at
`

type ConsumeMagicLinkByCodeParams struct {
	ID       string
	CodeHash string
}

func (q *Queries) ConsumeMagicLinkByCode(ctx context.Context, arg ConsumeMagicLinkByCodeParams) (AuthMagicLink, error) {
	row := q.db.QueryRowContext(ctx, consumeMagicLinkByCode, arg.ID, arg.CodeHash)
	var i AuthMagicLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthLogin = `-- name: CreateAuthLogin :one
INSERT INTO auth_logins (id, magic_link_id, org_id, user_id, role, email)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, magic_link_id, org_id, user_id, role, email, created_at
`

type CreateAuthLoginParams struct {
	ID          string
	MagicLinkID string
	OrgID       string
	UserID      string
	Role        string
	Email       string
}

func (q *Queries) CreateAuthLogin(ctx context.Context, arg CreateAuthLoginParams) (AuthLogin, error) {
	row := q.db.QueryRowContext(ctx, createAuthLogin,
		arg.ID,
		arg.MagicLinkID,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.Email,
	)
	var i AuthLogin
	err := row.Scan(
		&i.ID,
		&i.MagicLinkID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const createMagicLink = `-- name: CreateMagicLink :one
INSERT INTO auth_magic_links (id, org_id, email, code_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, email, code_hash, expires_at, consumed_at, created_at
`

type CreateMagicLinkParams struct {
	ID        string
	OrgID     string
	Email     string
	CodeHash  string
	ExpiresAt time.Time
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (AuthMagicLink, error) {
	row := q.db.QueryRowContext(ctx, createMagicLink,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i AuthMagicLink
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO auth_refresh_tokens (id, org_id, user_id, token_hash, session_id, device_info, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, user_id, token_hash, session_id, device_info, expires_at, revoked_at, last_used_at, created_at
`

type CreateRefreshTokenParams struct {
	ID         string
	OrgID      string
	UserID     string
	TokenHash  string
	SessionID  string
	DeviceInfo sql.NullString
	ExpiresAt  time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (AuthRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.TokenHash,
		arg.SessionID,
		arg.DeviceInfo,
		arg.ExpiresAt,
	)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TokenHash,
		&i.SessionID,
		&i.DeviceInfo,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthLoginByMagicLinkID = `-- name: GetAuthLoginByMagicLinkID :one
SELECT id, magic_link_id, org_id, user_id, role, email, created_at
FROM auth_logins
WHERE magic_link_id = $1
`

func (q *Queries) GetAuthLoginByMagicLinkID(ctx context.Context, magicLinkID string) (AuthLogin, error) {
	row := q.db.QueryRowContext(ctx, getAuthLoginByMagicLinkID, magicLinkID)
	var i AuthLogin
	err := row.Scan(
		&i.ID,
		&i.MagicLinkID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT id, org_id, user_id, token_hash, session_id, device_info, expires_at, revoked_at, last_used_at, created_at
FROM auth_refresh_tokens
WHERE id = $1 AND org_id = $2
`

type GetRefreshTokenByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetRefreshTokenByID(ctx context.Context, arg GetRefreshTokenByIDParams) (AuthRefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByID, arg.ID, arg.OrgID)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TokenHash,
		&i.SessionID,
		&i.DeviceInfo,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE auth_refresh_tokens
SET revoked_at = NOW()
WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	ID    string
	OrgID string
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeRefreshToken, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchRefreshToken = `-- name: TouchRefreshToken :execrows
UPDATE auth_refresh_tokens
SET last_used_at = NOW()
WHERE id = $1
  AND org_id = $2
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

type TouchRefreshTokenParams struct {
	ID    string
	OrgID string
}

func (q *Queries) TouchRefreshToken(ctx context.Context, arg TouchRefreshTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchRefreshToken, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
