// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health_checks.sql

package dbquery

import (
	"context"
)

const createHealthCheck = `-- name: CreateHealthCheck :one
INSERT INTO health_checks (service)
VALUES ($1)
RETURNING id, service, checked_at
`

func (q *Queries) CreateHealthCheck(ctx context.Context, service string) (HealthCheck, error) {
	row := q.db.QueryRowContext(ctx, createHealthCheck, service)
	var i HealthCheck
	err := row.Scan(&i.ID, &i.Service, &i.CheckedAt)
	return i, err
}

const listHealthChecks = `-- name: ListHealthChecks :many
SELECT id, service, checked_at
FROM health_checks
ORDER BY checked_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListHealthChecks(ctx context.Context, limit int32) ([]HealthCheck, error) {
	rows, err := q.db.QueryContext(ctx, listHealthChecks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthCheck
	for rows.Next() {
		var i HealthCheck
		if err := rows.Scan(&i.ID, &i.Service, &i.CheckedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
