// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package dbquery

import (
	"context"
)

const addTeamAdminScope = `-- name: AddTeamAdminScope :one
INSERT INTO team_admin_scopes (org_id, team_id, admin_user_id)
VALUES ($1, $2, $3)
RETURNING org_id, team_id, admin_user_id, created_at
`

type AddTeamAdminScopeParams struct {
	OrgID       string
	TeamID      string
	AdminUserID string
}

func (q *Queries) AddTeamAdminScope(ctx context.Context, arg AddTeamAdminScopeParams) (TeamAdminScope, error) {
	row := q.db.QueryRowContext(ctx, addTeamAdminScope, arg.OrgID, arg.TeamID, arg.AdminUserID)
	var i TeamAdminScope
	err := row.Scan(
		&i.OrgID,
		&i.TeamID,
		&i.AdminUserID,
		&i.CreatedAt,
	)
	return i, err
}

const addTeamMembership = `-- name: AddTeamMembership :one
INSERT INTO team_memberships (org_id, team_id, user_id)
VALUES ($1, $2, $3)
RETURNING org_id, team_id, user_id, created_at
`

type AddTeamMembershipParams struct {
	OrgID  string
	TeamID string
	UserID string
}

func (q *Queries) AddTeamMembership(ctx context.Context, arg AddTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRowContext(ctx, addTeamMembership, arg.OrgID, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.OrgID,
		&i.TeamID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listOrgMembershipsByOrg = `-- name: ListOrgMembershipsByOrg :many
SELECT org_id, user_id, role, created_at
FROM org_memberships
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListOrgMembershipsByOrgParams struct {
	OrgID string
	Limit int32
}

func (q *Queries) ListOrgMembershipsByOrg(ctx context.Context, arg ListOrgMembershipsByOrgParams) ([]OrgMembership, error) {
	rows, err := q.db.QueryContext(ctx, listOrgMembershipsByOrg, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgMembership
	for rows.Next() {
		var i OrgMembership
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamAdminScopes = `-- name: ListTeamAdminScopes :many
SELECT org_id, team_id, admin_user_id, created_at
FROM team_admin_scopes
WHERE org_id = $1 AND admin_user_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListTeamAdminScopesParams struct {
	OrgID       string
	AdminUserID string
	Limit       int32
}

func (q *Queries) ListTeamAdminScopes(ctx context.Context, arg ListTeamAdminScopesParams) ([]TeamAdminScope, error) {
	rows, err := q.db.QueryContext(ctx, listTeamAdminScopes, arg.OrgID, arg.AdminUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamAdminScope
	for rows.Next() {
		var i TeamAdminScope
		if err := rows.Scan(
			&i.OrgID,
			&i.TeamID,
			&i.AdminUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMemberships = `-- name: ListTeamMemberships :many
SELECT org_id, team_id, user_id, created_at
FROM team_memberships
WHERE org_id = $1 AND team_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListTeamMembershipsParams struct {
	OrgID  string
	TeamID string
	Limit  int32
}

func (q *Queries) ListTeamMemberships(ctx context.Context, arg ListTeamMembershipsParams) ([]TeamMembership, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMemberships, arg.OrgID, arg.TeamID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMembership
	for rows.Next() {
		var i TeamMembership
		if err := rows.Scan(
			&i.OrgID,
			&i.TeamID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrgMembership = `-- name: UpsertOrgMembership :one
INSERT INTO org_memberships (org_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, user_id)
DO UPDATE SET role = EXCLUDED.role
RETURNING org_id, user_id, role, created_at
`

type UpsertOrgMembershipParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) UpsertOrgMembership(ctx context.Context, arg UpsertOrgMembershipParams) (OrgMembership, error) {
	row := q.db.QueryRowContext(ctx, upsertOrgMembership, arg.OrgID, arg.UserID, arg.Role)
	var i OrgMembership
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
