// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_pricing.sql

package dbquery

import (
	"context"
	"database/sql"
	"time"
)

const closeActiveModelPricing = `-- name: CloseActiveModelPricing :execrows
UPDATE model_pricing
SET effective_to = $3
WHERE provider = $1
  AND model = $2
  AND effective_to IS NULL
  AND effective_from < $3
`

type CloseActiveModelPricingParams struct {
	Provider    string
	Model       string
	EffectiveTo sql.NullTime
}

func (q *Queries) CloseActiveModelPricing(ctx context.Context, arg CloseActiveModelPricingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeActiveModelPricing, arg.Provider, arg.Model, arg.EffectiveTo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createModelPricing = `-- name: CreateModelPricing :one
INSERT INTO model_pricing (
  provider,
  model,
  input_price_per_mtok,
  output_price_per_mtok,
  currency,
  source,
  effective_from
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, provider, model, input_price_per_mtok, output_price_per_mtok, currency, source, effective_from, effective_to, created_at
`

type CreateModelPricingParams struct {
	Provider           string
	Model              string
	InputPricePerMtok  float64
	OutputPricePerMtok float64
	Currency           string
	Source             string
	EffectiveFrom      time.Time
}

func (q *Queries) CreateModelPricing(ctx context.Context, arg CreateModelPricingParams) (ModelPricing, error) {
	row := q.db.QueryRowContext(ctx, createModelPricing,
		arg.Provider,
		arg.Model,
		arg.InputPricePerMtok,
		arg.OutputPricePerMtok,
		arg.Currency,
		arg.Source,
		arg.EffectiveFrom,
	)
	var i ModelPricing
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.InputPricePerMtok,
		&i.OutputPricePerMtok,
		&i.Currency,
		&i.Source,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveModelPricingByProviderModel = `-- name: GetActiveModelPricingByProviderModel :one
SELECT id, provider, model, input_price_per_mtok, output_price_per_mtok, currency, source, effective_from, effective_to, created_at
FROM model_pricing
WHERE provider = $1
  AND model = $2
  AND effective_to IS NULL
ORDER BY effective_from DESC
LIMIT 1
`

type GetActiveModelPricingByProviderModelParams struct {
	Provider string
	Model    string
}

func (q *Queries) GetActiveModelPricingByProviderModel(ctx context.Context, arg GetActiveModelPricingByProviderModelParams) (ModelPricing, error) {
	row := q.db.QueryRowContext(ctx, getActiveModelPricingByProviderModel, arg.Provider, arg.Model)
	var i ModelPricing
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.InputPricePerMtok,
		&i.OutputPricePerMtok,
		&i.Currency,
		&i.Source,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveModelPricing = `-- name: ListActiveModelPricing :many
SELECT id, provider, model, input_price_per_mtok, output_price_per_mtok, currency, source, effective_from, effective_to, created_at
FROM model_pricing
WHERE effective_to IS NULL
ORDER BY provider, model, effective_from DESC
`

func (q *Queries) ListActiveModelPricing(ctx context.Context) ([]ModelPricing, error) {
	rows, err := q.db.QueryContext(ctx, listActiveModelPricing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelPricing
	for rows.Next() {
		var i ModelPricing
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.InputPricePerMtok,
			&i.OutputPricePerMtok,
			&i.Currency,
			&i.Source,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
