// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package dbquery

import (
	"context"
)

const listOrgAllowedModels = `-- name: ListOrgAllowedModels :many
SELECT org_id, provider, model, is_allowed, created_at
FROM org_model_policies
WHERE org_id = $1 AND is_allowed = TRUE
ORDER BY provider, model
`

func (q *Queries) ListOrgAllowedModels(ctx context.Context, orgID string) ([]OrgModelPolicy, error) {
	rows, err := q.db.QueryContext(ctx, listOrgAllowedModels, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgModelPolicy
	for rows.Next() {
		var i OrgModelPolicy
		if err := rows.Scan(
			&i.OrgID,
			&i.Provider,
			&i.Model,
			&i.IsAllowed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamModelPolicies = `-- name: ListTeamModelPolicies :many
SELECT org_id, team_id, provider, model, is_allowed, created_at
FROM team_model_policies
WHERE org_id = $1 AND team_id = $2
ORDER BY provider, model
`

type ListTeamModelPoliciesParams struct {
	OrgID  string
	TeamID string
}

func (q *Queries) ListTeamModelPolicies(ctx context.Context, arg ListTeamModelPoliciesParams) ([]TeamModelPolicy, error) {
	rows, err := q.db.QueryContext(ctx, listTeamModelPolicies, arg.OrgID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamModelPolicy
	for rows.Next() {
		var i TeamModelPolicy
		if err := rows.Scan(
			&i.OrgID,
			&i.TeamID,
			&i.Provider,
			&i.Model,
			&i.IsAllowed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrgModelPolicy = `-- name: UpsertOrgModelPolicy :one
INSERT INTO org_model_policies (org_id, provider, model, is_allowed)
VALUES ($1, $2, $3, $4)
ON CONFLICT (org_id, provider, model)
DO UPDATE SET is_allowed = EXCLUDED.is_allowed
RETURNING org_id, provider, model, is_allowed, created_at
`

type UpsertOrgModelPolicyParams struct {
	OrgID     string
	Provider  string
	Model     string
	IsAllowed bool
}

func (q *Queries) UpsertOrgModelPolicy(ctx context.Context, arg UpsertOrgModelPolicyParams) (OrgModelPolicy, error) {
	row := q.db.QueryRowContext(ctx, upsertOrgModelPolicy,
		arg.OrgID,
		arg.Provider,
		arg.Model,
		arg.IsAllowed,
	)
	var i OrgModelPolicy
	err := row.Scan(
		&i.OrgID,
		&i.Provider,
		&i.Model,
		&i.IsAllowed,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTeamModelPolicy = `-- name: UpsertTeamModelPolicy :one
INSERT INTO team_model_policies (org_id, team_id, provider, model, is_allowed)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, team_id, provider, model)
DO UPDATE SET is_allowed = EXCLUDED.is_allowed
RETURNING org_id, team_id, provider, model, is_allowed, created_at
`

type UpsertTeamModelPolicyParams struct {
	OrgID     string
	TeamID    string
	Provider  string
	Model     string
	IsAllowed bool
}

func (q *Queries) UpsertTeamModelPolicy(ctx context.Context, arg UpsertTeamModelPolicyParams) (TeamModelPolicy, error) {
	row := q.db.QueryRowContext(ctx, upsertTeamModelPolicy,
		arg.OrgID,
		arg.TeamID,
		arg.Provider,
		arg.Model,
		arg.IsAllowed,
	)
	var i TeamModelPolicy
	err := row.Scan(
		&i.OrgID,
		&i.TeamID,
		&i.Provider,
		&i.Model,
		&i.IsAllowed,
		&i.CreatedAt,
	)
	return i, err
}
