// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_keys.sql

package dbquery

import (
	"context"
)

const createOrgProviderKey = `-- name: CreateOrgProviderKey :one
INSERT INTO org_provider_keys (id, org_id, provider, key_ciphertext, key_nonce, key_kek_id, is_active)
VALUES ($1, $2, $3, $4, $5, $6, TRUE)
RETURNING id, org_id, provider, key_ciphertext, key_nonce, key_kek_id, is_active, created_at, updated_at
`

type CreateOrgProviderKeyParams struct {
	ID            string
	OrgID         string
	Provider      string
	KeyCiphertext []byte
	KeyNonce      []byte
	KeyKekID      string
}

func (q *Queries) CreateOrgProviderKey(ctx context.Context, arg CreateOrgProviderKeyParams) (OrgProviderKey, error) {
	row := q.db.QueryRowContext(ctx, createOrgProviderKey,
		arg.ID,
		arg.OrgID,
		arg.Provider,
		arg.KeyCiphertext,
		arg.KeyNonce,
		arg.KeyKekID,
	)
	var i OrgProviderKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.KeyCiphertext,
		&i.KeyNonce,
		&i.KeyKekID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgProviderKeyByID = `-- name: GetOrgProviderKeyByID :one
SELECT id, org_id, provider, key_ciphertext, key_nonce, key_kek_id, is_active, created_at, updated_at
FROM org_provider_keys
WHERE id = $1
`

func (q *Queries) GetOrgProviderKeyByID(ctx context.Context, id string) (OrgProviderKey, error) {
	row := q.db.QueryRowContext(ctx, getOrgProviderKeyByID, id)
	var i OrgProviderKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.KeyCiphertext,
		&i.KeyNonce,
		&i.KeyKekID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
