// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: router_lookup.sql

package dbquery

import (
	"context"
	"database/sql"
	"time"
)

const listEffectiveAllowedModels = `-- name: ListEffectiveAllowedModels :many
SELECT o.provider, o.model
FROM org_model_policies AS o
LEFT JOIN team_model_policies AS t
  ON t.org_id = o.org_id
 AND t.team_id = $2
 AND t.provider = o.provider
 AND t.model = o.model
WHERE o.org_id = $1
  AND o.is_allowed = TRUE
  AND COALESCE(t.is_allowed, TRUE) = TRUE
ORDER BY o.provider, o.model
LIMIT $4
OFFSET COALESCE($3::int, 0)
`

type ListEffectiveAllowedModelsParams struct {
	OrgID      string
	TeamID     string
	OffsetRows sql.NullInt32
	LimitRows  int32
}

type ListEffectiveAllowedModelsRow struct {
	Provider string
	Model    string
}

func (q *Queries) ListEffectiveAllowedModels(ctx context.Context, arg ListEffectiveAllowedModelsParams) ([]ListEffectiveAllowedModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEffectiveAllowedModels,
		arg.OrgID,
		arg.TeamID,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEffectiveAllowedModelsRow
	for rows.Next() {
		var i ListEffectiveAllowedModelsRow
		if err := rows.Scan(&i.Provider, &i.Model); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveIdentityByAPIKeyHash = `-- name: ResolveIdentityByAPIKeyHash :one
SELECT id, org_id, team_id, user_id, key_prefix, revoked_at, is_active, last_used_at, created_at
FROM user_team_api_keys
WHERE key_hash = $1
  AND is_active = TRUE
  AND revoked_at IS NULL
`

type ResolveIdentityByAPIKeyHashRow struct {
	ID         string
	OrgID      string
	TeamID     string
	UserID     string
	KeyPrefix  string
	RevokedAt  sql.NullTime
	IsActive   bool
	LastUsedAt sql.NullTime
	CreatedAt  time.Time
}

func (q *Queries) ResolveIdentityByAPIKeyHash(ctx context.Context, keyHash string) (ResolveIdentityByAPIKeyHashRow, error) {
	row := q.db.QueryRowContext(ctx, resolveIdentityByAPIKeyHash, keyHash)
	var i ResolveIdentityByAPIKeyHashRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TeamID,
		&i.UserID,
		&i.KeyPrefix,
		&i.RevokedAt,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}
