// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package dbquery

import (
	"context"
	"database/sql"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, org_id, name, profile_jsonb, rate_limit_per_minute)
VALUES ($1, $2, $3, COALESCE($4, '{}'::jsonb), $5)
RETURNING id, org_id, name, profile_jsonb, rate_limit_per_minute, created_at, updated_at
`

type CreateTeamParams struct {
	ID                 string
	OrgID              string
	Name               string
	Column4            interface{}
	RateLimitPerMinute sql.NullInt32
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Column4,
		arg.RateLimitPerMinute,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ProfileJsonb,
		&i.RateLimitPerMinute,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, org_id, name, profile_jsonb, rate_limit_per_minute, created_at, updated_at
FROM teams
WHERE id = $1 AND org_id = $2
`

type GetTeamByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetTeamByID(ctx context.Context, arg GetTeamByIDParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, arg.ID, arg.OrgID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ProfileJsonb,
		&i.RateLimitPerMinute,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamsByOrg = `-- name: ListTeamsByOrg :many
SELECT id, org_id, name, profile_jsonb, rate_limit_per_minute, created_at, updated_at
FROM teams
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListTeamsByOrgParams struct {
	OrgID string
	Limit int32
}

func (q *Queries) ListTeamsByOrg(ctx context.Context, arg ListTeamsByOrgParams) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeamsByOrg, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.ProfileJsonb,
			&i.RateLimitPerMinute,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
