// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage_logs.sql

package dbquery

import (
	"context"
	"database/sql"
)

const createUsageLog = `-- name: CreateUsageLog :one
INSERT INTO usage_logs (
  org_id,
  team_id,
  user_id,
  api_key_id,
  provider,
  model,
  request_tokens,
  response_tokens,
  latency_ms,
  status_code,
  request_fingerprint
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, team_id, user_id, api_key_id, provider, model, request_tokens, response_tokens, latency_ms, status_code, request_fingerprint, created_at
`

type CreateUsageLogParams struct {
	OrgID              string
	TeamID             string
	UserID             string
	ApiKeyID           string
	Provider           string
	Model              string
	RequestTokens      int32
	ResponseTokens     int32
	LatencyMs          int32
	StatusCode         int32
	RequestFingerprint sql.NullString
}

func (q *Queries) CreateUsageLog(ctx context.Context, arg CreateUsageLogParams) (UsageLog, error) {
	row := q.db.QueryRowContext(ctx, createUsageLog,
		arg.OrgID,
		arg.TeamID,
		arg.UserID,
		arg.ApiKeyID,
		arg.Provider,
		arg.Model,
		arg.RequestTokens,
		arg.ResponseTokens,
		arg.LatencyMs,
		arg.StatusCode,
		arg.RequestFingerprint,
	)
	var i UsageLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TeamID,
		&i.UserID,
		&i.ApiKeyID,
		&i.Provider,
		&i.Model,
		&i.RequestTokens,
		&i.ResponseTokens,
		&i.LatencyMs,
		&i.StatusCode,
		&i.RequestFingerprint,
		&i.CreatedAt,
	)
	return i, err
}
